<a href="https://colab.research.google.com/github/jbliaw/NBA_Player_Youtube/blob/main/NBA_Player_Analysis1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NBA Player Analysis

Link to Youtube tutorial: https://www.youtube.com/watch?v=_t3c2VM3PWk&ab_channel=TwoWayStopSign

In [ ]:
# Necessary Imports
import pandas as pd

In [ ]:
# Read in the data using direct upload to Google Colab
df = pd.read_csv('all_seasons.csv', index_col=0)

df.head() # Take a look at the top of the data

         player_name team_abbreviation   age  ...  ts_pct  ast_pct   season
0      Dennis Rodman               CHI  36.0  ...   0.479    0.113  1996-97
1  Dwayne Schintzius               LAC  28.0  ...   0.430    0.048  1996-97
2       Earl Cureton               TOR  39.0  ...   0.376    0.148  1996-97
3        Ed O'Bannon               DAL  24.0  ...   0.399    0.077  1996-97
4        Ed Pinckney               MIA  34.0  ...   0.611    0.040  1996-97

[5 rows x 21 columns]

In [ ]:
# Read in the data using url from Github
url = 'https://raw.githubusercontent.com/jbliaw/NBA_Player_Youtube/main/all_seasons.csv'
using_url = pd.read_csv(url, index_col=0)
using_url.head()

In [ ]:
df.shape # (# of rows, # of columns)

(11145, 21)

In [ ]:
df.describe() # Get an idea of what the numerical values of the data consist of

                age  player_height  ...        ts_pct       ast_pct
count  11145.000000   11145.000000  ...  11145.000000  11145.000000
mean      27.168686     200.812818  ...      0.508099      0.131078
std        4.344164       9.190973  ...      0.098879      0.095017
min       18.000000     160.020000  ...      0.000000      0.000000
25%       24.000000     195.580000  ...      0.478000      0.065000
50%       27.000000     200.660000  ...      0.521000      0.102000
75%       30.000000     208.280000  ...      0.557000      0.178000
max       44.000000     231.140000  ...      1.500000      1.000000

[8 rows x 13 columns]

In [ ]:
df.tail() # Take a look at the bottom of the data

              player_name team_abbreviation   age  ...  ts_pct  ast_pct   season
11140         Maxi Kleber               DAL  28.0  ...   0.605    0.064  2019-20
11141  Melvin Frazier Jr.               ORL  23.0  ...   0.480    0.033  2019-20
11142      Meyers Leonard               MIA  28.0  ...   0.640    0.076  2019-20
11143        Norvel Pelle               PHI  27.0  ...   0.521    0.056  2019-20
11144         Matt Thomas               TOR  25.0  ...   0.663    0.089  2019-20

[5 rows x 21 columns]

## Task 1: Cleaning the data
Note: Cleaning the data is generally a continuous thing. Often times, you won't know exactly what you'll need to clean until you run into a problem with the analysis. This is simply an introduction to some tools you can use to clean the data.

In [ ]:
# Take out the 2019 data because incomplete

df = df.loc[~df['season'].str.contains('2019-20')]
df.tail()

         player_name team_abbreviation   age  ...  ts_pct  ast_pct   season
10626    Abdel Nader               OKC  25.0  ...   0.522    0.044  2018-19
10627  Aaron Holiday               IND  22.0  ...   0.518    0.180  2018-19
10628   Aaron Gordon               ORL  23.0  ...   0.538    0.166  2018-19
10629     Alec Burks               SAC  27.0  ...   0.523    0.142  2018-19
10630   Zhaire Smith               PHI  20.0  ...   0.533    0.101  2018-19

[5 rows x 21 columns]

In [ ]:
# Null or NaN values

# .isna() and .isnull() are aliases of each other and essentially do the same thing
#df.isna().sum()
df.isnull().sum()

# Adding additional parameters
    #  - Using .any() says select rows/columns that have NaN's in any of them
    #  - Using .all() says select rows/columns that are completely NaN values
    #  - Axis key: 0 is column, 1 is row
#df.isna().any(axis=0) 
#df.isna().all(axis=1)

player_name          0
team_abbreviation    0
age                  0
player_height        0
player_weight        0
college              0
country              0
draft_year           0
draft_round          0
draft_number         0
gp                   0
pts                  0
reb                  0
ast                  0
net_rating           0
oreb_pct             0
dreb_pct             0
usg_pct              0
ts_pct               0
ast_pct              0
season               0
dtype: int64

In [ ]:
# Setting decimal points
df.player_weight = df.player_weight.round(decimals=3)
df.head()

         player_name team_abbreviation   age  ...  ts_pct  ast_pct   season
0      Dennis Rodman               CHI  36.0  ...   0.479    0.113  1996-97
1  Dwayne Schintzius               LAC  28.0  ...   0.430    0.048  1996-97
2       Earl Cureton               TOR  39.0  ...   0.376    0.148  1996-97
3        Ed O'Bannon               DAL  24.0  ...   0.399    0.077  1996-97
4        Ed Pinckney               MIA  34.0  ...   0.611    0.040  1996-97

[5 rows x 21 columns]

In [ ]:
# Check for duplicated rows
df.duplicated(subset=None, keep='first').sum()
# Subset allows you to select a certain row or column
# Keep only the 'first' instance of the duplicate
# .sum() or .count() to count the number of duplicates

0

In [ ]:
# Creating new variable season_year so that it can be more easily graphed/analyzed over time, etc.
# Basically an 'if statement'

df.loc[df['season'] == '1996-97', 'season_year'] = 1996
df.loc[df['season'] == '1997-98', 'season_year'] = 1997
df.loc[df['season'] == '1998-99', 'season_year'] = 1998
df.loc[df['season'] == '1999-00', 'season_year'] = 1999
df.loc[df['season'] == '2000-01', 'season_year'] = 2000
df.loc[df['season'] == '2001-02', 'season_year'] = 2001
df.loc[df['season'] == '2002-03', 'season_year'] = 2002
df.loc[df['season'] == '2003-04', 'season_year'] = 2003
df.loc[df['season'] == '2004-05', 'season_year'] = 2004
df.loc[df['season'] == '2005-06', 'season_year'] = 2005
df.loc[df['season'] == '2006-07', 'season_year'] = 2006
df.loc[df['season'] == '2007-08', 'season_year'] = 2007
df.loc[df['season'] == '2008-09', 'season_year'] = 2008
df.loc[df['season'] == '2009-10', 'season_year'] = 2009
df.loc[df['season'] == '2010-11', 'season_year'] = 2010
df.loc[df['season'] == '2011-12', 'season_year'] = 2011
df.loc[df['season'] == '2012-13', 'season_year'] = 2012
df.loc[df['season'] == '2013-14', 'season_year'] = 2013
df.loc[df['season'] == '2014-15', 'season_year'] = 2014
df.loc[df['season'] == '2015-16', 'season_year'] = 2015
df.loc[df['season'] == '2016-17', 'season_year'] = 2016
df.loc[df['season'] == '2017-18', 'season_year'] = 2017
df.loc[df['season'] == '2018-19', 'season_year'] = 2018

df

             player_name team_abbreviation   age  ...  ast_pct   season season_year
0          Dennis Rodman               CHI  36.0  ...    0.113  1996-97      1996.0
1      Dwayne Schintzius               LAC  28.0  ...    0.048  1996-97      1996.0
2           Earl Cureton               TOR  39.0  ...    0.148  1996-97      1996.0
3            Ed O'Bannon               DAL  24.0  ...    0.077  1996-97      1996.0
4            Ed Pinckney               MIA  34.0  ...    0.040  1996-97      1996.0
...                  ...               ...   ...  ...      ...      ...         ...
10626        Abdel Nader               OKC  25.0  ...    0.044  2018-19      2018.0
10627      Aaron Holiday               IND  22.0  ...    0.180  2018-19      2018.0
10628       Aaron Gordon               ORL  23.0  ...    0.166  2018-19      2018.0
10629         Alec Burks               SAC  27.0  ...    0.142  2018-19      2018.0
10630       Zhaire Smith               PHI  20.0  ...    0.101  2018-19      2018.0

[10631 rows x 22 columns]

In [ ]:
df.head(20) # You can see here that there are Undrafted players

          player_name team_abbreviation   age  ...  ast_pct   season season_year
0       Dennis Rodman               CHI  36.0  ...    0.113  1996-97      1996.0
1   Dwayne Schintzius               LAC  28.0  ...    0.048  1996-97      1996.0
2        Earl Cureton               TOR  39.0  ...    0.148  1996-97      1996.0
3         Ed O'Bannon               DAL  24.0  ...    0.077  1996-97      1996.0
4         Ed Pinckney               MIA  34.0  ...    0.040  1996-97      1996.0
5       Eddie Johnson               HOU  38.0  ...    0.102  1996-97      1996.0
6         Eddie Jones               LAL  25.0  ...    0.149  1996-97      1996.0
7      Elden Campbell               LAL  28.0  ...    0.087  1996-97      1996.0
8   Eldridge Recasner               ATL  29.0  ...    0.141  1996-97      1996.0
9        Elliot Perry               MIL  28.0  ...    0.262  1996-97      1996.0
10      Elmer Bennett               DEN  27.0  ...    0.216  1996-97      1996.0
11     Elmore Spencer               SEA  27.0  ...    0.000  1996-97      1996.0
12      Emanual Davis               HOU  28.0  ...    0.191  1996-97      1996.0
13      Ennis Whatley               POR  34.0  ...    0.375  1996-97      1996.0
14       Eric Leckner               VAN  31.0  ...    0.067  1996-97      1996.0
15        Eric Mobley               VAN  27.0  ...    0.076  1996-97      1996.0
16      Eric Montross               NJN  25.0  ...    0.050  1996-97      1996.0
17       Eric Murdock               DEN  29.0  ...    0.436  1996-97      1996.0
18    Eric Piatkowski               LAC  26.0  ...    0.111  1996-97      1996.0
19          Eric Snow               SEA  24.0  ...    0.339  1996-97      1996.0

[20 rows x 22 columns]

In [ ]:
# Removing Undrafted players and making that into a new dataframe named no_undrafted
no_undrafted = df.loc[~df['draft_number'].str.contains('Undrafted')]
no_undrafted.head(20)

          player_name team_abbreviation   age  ...  ast_pct   season season_year
0       Dennis Rodman               CHI  36.0  ...    0.113  1996-97      1996.0
1   Dwayne Schintzius               LAC  28.0  ...    0.048  1996-97      1996.0
2        Earl Cureton               TOR  39.0  ...    0.148  1996-97      1996.0
3         Ed O'Bannon               DAL  24.0  ...    0.077  1996-97      1996.0
4         Ed Pinckney               MIA  34.0  ...    0.040  1996-97      1996.0
5       Eddie Johnson               HOU  38.0  ...    0.102  1996-97      1996.0
6         Eddie Jones               LAL  25.0  ...    0.149  1996-97      1996.0
7      Elden Campbell               LAL  28.0  ...    0.087  1996-97      1996.0
9        Elliot Perry               MIL  28.0  ...    0.262  1996-97      1996.0
10      Elmer Bennett               DEN  27.0  ...    0.216  1996-97      1996.0
11     Elmore Spencer               SEA  27.0  ...    0.000  1996-97      1996.0
13      Ennis Whatley               POR  34.0  ...    0.375  1996-97      1996.0
14       Eric Leckner               VAN  31.0  ...    0.067  1996-97      1996.0
15        Eric Mobley               VAN  27.0  ...    0.076  1996-97      1996.0
16      Eric Montross               NJN  25.0  ...    0.050  1996-97      1996.0
17       Eric Murdock               DEN  29.0  ...    0.436  1996-97      1996.0
18    Eric Piatkowski               LAC  26.0  ...    0.111  1996-97      1996.0
19          Eric Snow               SEA  24.0  ...    0.339  1996-97      1996.0
20      Eric Williams               BOS  24.0  ...    0.087  1996-97      1996.0
21      Erick Dampier               IND  21.0  ...    0.074  1996-97      1996.0

[20 rows x 22 columns]